version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/UnzipResourceBundle.sh
    - location: scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/RunFunctionalTests.sh
      timeout: 240
  ValidateService:
    - location: scripts/MonitorService.sh
      timeout: 30
      runas: codedeployuser
