version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/minipetpee-backend
hooks:
  AfterInstall:
    - location: scripts/set_owner.sh
      timeout: 5
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 30
      runas: ec2-user