# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: minipetpee-backend CI&CD with Gradle

on:
  push:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'hotspot'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean & Build with Gradle
      run: ./gradlew clean build

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.19
      if: always()
      with:
        files: build/test-results/**/*.xml
